spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: arvin27021379
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect